matrix:
  - name: Markdown
    aspell:
      lang: en
      ignore-case: true
    dictionary:
      wordlists:
        - config/wordlist.txt
      encoding: utf-8
    pipeline:
      - pyspelling.filters.html:
          comments: false
          ignores:
            - code
            - pre
    sources:
      - "**/*.mdx"
    default_encoding: utf-8
